import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Find where to incorporate AUTH, should be in _app using NextAUTH */}

      {/* Menu */}

      {/* Feed */}
    </div>
  );
}
