import Head from "next/head";
import Feed from "../lib/components/Feed/Feed";
import Menu from "../lib/components/Menu/Menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center h-screen py-12">

        <Menu />

        <Feed />
      </main>
    </div>
  );
}
